### ISSUE TITLE
Unable to Install "sharp"

### ISSUE THREAD

**Issue by jcalabro** [PatrickTorgerson/fenlense#1]
Hey there, would love to use this extension! However, I'm getting an error when installing and trying to activate the extension. Any advice?

```
2023-08-31 21:03:09.586 [error] Activating extension dullptr.fen-lense failed due to an error:
2023-08-31 21:03:09.586 [error] Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-darwin-arm64v8.node'
Require stack:
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/node_modules/sharp/lib/sharp.js
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/node_modules/sharp/lib/constructor.js
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/node_modules/sharp/lib/index.js
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/out/images.js
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/out/fenlense.js
- /Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
- 

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current darwin-arm64v8 runtime: "npm install --platform=darwin --arch=arm64v8 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
```

I was able to `npm install sharp` no problem. Any idea on how I should go about installing this? Thanks!

```
$ node -v
v20.3.0

$ npm -v
9.6.7
```

**Comment by PatrickTorgerson** [comment]
sharp may be building for the wrong platform, check the `/Users/jcalabro/.vscode/extensions/dullptr.fen-lense-0.1.1/node_modules/sharp/build/Release` directory. As a temporary solution you could copy the build artifacts from your local install into the above build dir.

I will look into a more permanent solution

**Comment by PatrickTorgerson** [comment]
okay, I've published an update that may solve this issue. I don't have access to a non windows machine to test so if you @jcalabro could reinstall the extension and let me know if the issue is resolved I would appreciate it

**Comment by jcalabro** [comment]
Hmm, the update did not solve the issue, but I was able to manually solve it by:

```
cd ~/.vscode/extensions/dullptr.fen-lense-0.1.3
npm install
```

That npm install worked without issue, and now I'm off to the races:

<img width="1840" alt="Screenshot 2023-09-01 at 7 12 50 AM" src="https://github.com/PatrickTorgerson/fenlense/assets/8205547/f0e68521-55a6-4feb-a2dc-7758245a70a8">

Happy to help run commands or reinstall if you need a machine that can repro?

**Comment by PatrickTorgerson** [comment]
@jcalabro I have a new update out that should solve this issue, tested in a linux vm. If you want to reinstall and verify I can close this issue

**Comment by jcalabro** [comment]
Worked for me. Thanks a ton! :100:
